spring:
  cloud:
    azure:
      cosmos:
        database: springbasic
        populate-query-metrics: true
        endpoint: https://springappservicewithgitdb.documents.azure.com:443/
        key: oNSEvjYvdYqt1094teQ0dolS4YQP3eZq45wBkl317aKGbDKYNSKJGMBFQZ0NOt2sH4Bl8chUP0NKACDb2SE6AQ==